// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketType int32

const (
	PacketType_PACKET_TYPE PacketType = 0
	PacketType_QUERY       PacketType = 1
)

var PacketType_name = map[int32]string{
	0: "PACKET_TYPE",
	1: "QUERY",
}

var PacketType_value = map[string]int32{
	"PACKET_TYPE": 0,
	"QUERY":       1,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

type PacketReq struct {
	Index int32      `protobuf:"zigzag32,1,opt,name=index,proto3" json:"index,omitempty"`
	Type  PacketType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.PacketType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*PacketReq_HeartBeat
	Content              isPacketReq_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PacketReq) Reset()         { *m = PacketReq{} }
func (m *PacketReq) String() string { return proto.CompactTextString(m) }
func (*PacketReq) ProtoMessage()    {}
func (*PacketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *PacketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketReq.Unmarshal(m, b)
}
func (m *PacketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketReq.Marshal(b, m, deterministic)
}
func (m *PacketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketReq.Merge(m, src)
}
func (m *PacketReq) XXX_Size() int {
	return xxx_messageInfo_PacketReq.Size(m)
}
func (m *PacketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketReq.DiscardUnknown(m)
}

var xxx_messageInfo_PacketReq proto.InternalMessageInfo

func (m *PacketReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PacketReq) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_PACKET_TYPE
}

type isPacketReq_Content interface {
	isPacketReq_Content()
}

type PacketReq_HeartBeat struct {
	HeartBeat *Heartbeat `protobuf:"bytes,3,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

func (*PacketReq_HeartBeat) isPacketReq_Content() {}

func (m *PacketReq) GetContent() isPacketReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PacketReq) GetHeartBeat() *Heartbeat {
	if x, ok := m.GetContent().(*PacketReq_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PacketReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PacketReq_HeartBeat)(nil),
	}
}

type PacketRes struct {
	Index int32      `protobuf:"zigzag32,1,opt,name=index,proto3" json:"index,omitempty"`
	Type  PacketType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.PacketType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*PacketRes_HeartBeat
	Content              isPacketRes_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PacketRes) Reset()         { *m = PacketRes{} }
func (m *PacketRes) String() string { return proto.CompactTextString(m) }
func (*PacketRes) ProtoMessage()    {}
func (*PacketRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *PacketRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketRes.Unmarshal(m, b)
}
func (m *PacketRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketRes.Marshal(b, m, deterministic)
}
func (m *PacketRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketRes.Merge(m, src)
}
func (m *PacketRes) XXX_Size() int {
	return xxx_messageInfo_PacketRes.Size(m)
}
func (m *PacketRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketRes.DiscardUnknown(m)
}

var xxx_messageInfo_PacketRes proto.InternalMessageInfo

func (m *PacketRes) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PacketRes) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_PACKET_TYPE
}

type isPacketRes_Content interface {
	isPacketRes_Content()
}

type PacketRes_HeartBeat struct {
	HeartBeat *Heartbeat `protobuf:"bytes,3,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

func (*PacketRes_HeartBeat) isPacketRes_Content() {}

func (m *PacketRes) GetContent() isPacketRes_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PacketRes) GetHeartBeat() *Heartbeat {
	if x, ok := m.GetContent().(*PacketRes_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PacketRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PacketRes_HeartBeat)(nil),
	}
}

type Heartbeat struct {
	CTime                int64    `protobuf:"zigzag64,1,opt,name=c_time,json=cTime,proto3" json:"c_time,omitempty"`
	STime                int64    `protobuf:"zigzag64,2,opt,name=s_time,json=sTime,proto3" json:"s_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *Heartbeat) GetSTime() int64 {
	if m != nil {
		return m.STime
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*PacketReq)(nil), "proto.PacketReq")
	proto.RegisterType((*PacketRes)(nil), "proto.PacketRes")
	proto.RegisterType((*Heartbeat)(nil), "proto.Heartbeat")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x8f, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xb3, 0xb5, 0xa9, 0xec, 0x14, 0x34, 0x1d, 0x14, 0x82, 0xa7, 0x50, 0x10, 0x82, 0x87,
	0xa2, 0x11, 0x0f, 0x1e, 0x3c, 0x58, 0x09, 0x16, 0xbc, 0xc4, 0x35, 0x1e, 0x7a, 0x0a, 0xdb, 0x38,
	0xd4, 0x20, 0xf9, 0xd3, 0x64, 0x0e, 0xf6, 0x05, 0x7c, 0x6e, 0xc9, 0xae, 0x28, 0xf5, 0x05, 0x7a,
	0x5a, 0xf6, 0xf7, 0x7d, 0x33, 0xfc, 0x06, 0x60, 0xad, 0x4b, 0x9a, 0x35, 0x6d, 0xcd, 0x35, 0xba,
	0xe6, 0x99, 0x7e, 0x09, 0x90, 0x89, 0xce, 0x3f, 0x88, 0x15, 0x6d, 0xf0, 0x04, 0xdc, 0xa2, 0x7a,
	0xa3, 0x4f, 0x5f, 0x04, 0x22, 0x9c, 0x28, 0xfb, 0xc1, 0x73, 0x18, 0xf2, 0xb6, 0x21, 0x7f, 0x10,
	0x88, 0xf0, 0x28, 0x9a, 0xd8, 0x05, 0x33, 0x3b, 0x95, 0x6e, 0x1b, 0x52, 0x26, 0xc6, 0x2b, 0x80,
	0x77, 0xd2, 0x2d, 0x67, 0x2b, 0xd2, 0xec, 0x1f, 0x04, 0x22, 0x1c, 0x47, 0xde, 0x4f, 0x79, 0xd1,
	0x07, 0x3d, 0x5f, 0x38, 0x4a, 0x9a, 0xd6, 0x9c, 0x34, 0xcf, 0x25, 0x1c, 0xe6, 0x75, 0xc5, 0x54,
	0xf1, 0x8e, 0x48, 0xb7, 0x4f, 0x91, 0x5b, 0x90, 0xbf, 0x25, 0x3c, 0x85, 0x51, 0x9e, 0x71, 0x51,
	0x92, 0x11, 0x41, 0xe5, 0xe6, 0x69, 0x51, 0x52, 0x8f, 0x3b, 0x8b, 0x07, 0x16, 0x77, 0x3d, 0xbe,
	0x08, 0x01, 0xfe, 0x64, 0xf0, 0x18, 0xc6, 0xc9, 0xfd, 0xc3, 0x53, 0x9c, 0x66, 0xe9, 0x32, 0x89,
	0x3d, 0x07, 0x25, 0xb8, 0xcf, 0xaf, 0xb1, 0x5a, 0x7a, 0x22, 0xba, 0x83, 0xe1, 0xa3, 0x2e, 0x09,
	0x6f, 0x40, 0xbe, 0x70, 0x4b, 0xba, 0x2c, 0xaa, 0x35, 0x7a, 0x3b, 0x07, 0x29, 0xda, 0x9c, 0xfd,
	0x27, 0xdd, 0xd4, 0x09, 0xc5, 0xa5, 0x58, 0x8d, 0x0c, 0xbe, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0x1e, 0x68, 0xe0, 0xd1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	Streaming(ctx context.Context, opts ...grpc.CallOption) (Game_StreamingClient, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Streaming(ctx context.Context, opts ...grpc.CallOption) (Game_StreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/proto.Game/Streaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameStreamingClient{stream}
	return x, nil
}

type Game_StreamingClient interface {
	Send(*PacketReq) error
	Recv() (*PacketRes, error)
	grpc.ClientStream
}

type gameStreamingClient struct {
	grpc.ClientStream
}

func (x *gameStreamingClient) Send(m *PacketReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameStreamingClient) Recv() (*PacketRes, error) {
	m := new(PacketRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	Streaming(Game_StreamingServer) error
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_Streaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).Streaming(&gameStreamingServer{stream})
}

type Game_StreamingServer interface {
	Send(*PacketRes) error
	Recv() (*PacketReq, error)
	grpc.ServerStream
}

type gameStreamingServer struct {
	grpc.ServerStream
}

func (x *gameStreamingServer) Send(m *PacketRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameStreamingServer) Recv() (*PacketReq, error) {
	m := new(PacketReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Game",
	HandlerType: (*GameServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Streaming",
			Handler:       _Game_Streaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}
